server:
  port: 7766


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: your_username
    password: your_password
    #driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
#    openai:
#      api-key: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#      model: gpt-4-turbo
#      temperature: 0.7
#      max-tokens: 500
    ollama:
      base-url: http://120.46.189.218:11434
      chat:
        options:
          model: deepseek-r1:1.5b
    moonshot:
      api-key: sk-bNdwH7QV15EWWaEhh3PWXaWyfumnVSRhQ7K9KRvV0xcn51sp
      chat:
        options:
          model: moonshot-v1-8k
          temperature: 0.7
