server:
  port: 7776

spring:
  datasource:
    url: jdbc:postgresql://10.211.55.7:5432/embedding
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 60
      minimum-idle: 5
      connection-test-query: SELECT 1
      connection-init-sql: SELECT 1


langchain4j:
    community:
      dashscope:
        chat-model:
          api-key: sk-4000a9e2f25d469fb524a5174df01693
          #model_name:  deepseek-v3           qwen-max-latest    qwen-plus    qwq-32b
          model-name: qwen-max
        embedding-model:
          model-name: multimodal-embedding-v1
          base-url: https://dashscope.aliyuncs.com/api/v1/services/embeddings/multimodal-embedding/multimodal-embedding
          api-key: sk-4000a9e2f25d469fb524a5174df01693
        multimodal-model:
          model-name: multimodal-embedding-v1
#    ollama:
#      chat-model:
#        base-url: http://120.46.189.218:11434
#        #model-name: llama3.1
#        model-name: llama3.2:latest
#      embedding-model:
#        base-url: http://120.46.189.218:11434
#        model-name: all-minilm



pgvector:
  database: embedding
  host: 10.211.55.7
  port : 5432
  user: postgres
  password: postgres
  table: langchan4j_embedding

search:
  apiKey: gqcmTevJUpeuzabkZ8f7fF2p
  engine: baidu

